# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Eletto
email: john@johneletto.com
description: View John Eletto's resume and portfolio site. Student - Developer - Designer - Tutor
author: John Eletto
baseurl: "" # the subpath of your site, e.g. /blog
root: /octo-5
url: "http://johneletto.com" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown
